import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import { AuthKitProvider } from "@workos-inc/authkit-nextjs/components";
import { isWorkOSEnabled } from "@/lib/auth/client";
import { GlobalStateProvider } from "./contexts/GlobalState";
import { TodoBlockProvider } from "./contexts/TodoBlockContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
    <GlobalStateProvider>
      <TodoBlockProvider>
        <TooltipProvider>
          {children}
          <Toaster />
        </TooltipProvider>
      </TodoBlockProvider>
    </GlobalStateProvider>
  );

  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isWorkOSEnabled() ? (
          <AuthKitProvider>{content}</AuthKitProvider>
        ) : (
          content
        )}
      </body>
    </html>
  );
}
