import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import { AuthKitProvider } from "@workos-inc/authkit-nextjs/components";
import { isWorkOSEnabled } from "@/lib/auth-config";
import { GlobalStateProvider } from "./contexts/GlobalState";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
    <GlobalStateProvider>
      <TooltipProvider>
        {children}
        <Toaster />
      </TooltipProvider>
    </GlobalStateProvider>
  );

  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isWorkOSEnabled() ? (
          <AuthKitProvider>{content}</AuthKitProvider>
        ) : (
          content
        )}
      </body>
    </html>
  );
}
