#!/bin/sh
set -eu

custom_resolver=false
disable_update_check=-disable-update-check
for argument in "$@"; do
  case "$argument" in
    -r|--resolver|-r=*|--resolver=*)
      custom_resolver=true
      ;;
    -up|--update)
      disable_update_check=
      ;;
  esac
done

if [ "$custom_resolver" = true ]; then
  if [ -n "$disable_update_check" ]; then
    exec /usr/bin/naabu "$disable_update_check" "$@"
  fi
  exec /usr/bin/naabu "$@"
fi

resolver="$(awk '$1 == "nameserver" && $2 !~ /^127\./ { print $2; exit }' /etc/resolv.conf)"
if [ -n "$resolver" ]; then
  if [ -n "$disable_update_check" ]; then
    exec /usr/bin/naabu "$disable_update_check" -r "$resolver" "$@"
  fi
  exec /usr/bin/naabu -r "$resolver" "$@"
fi

if [ -n "$disable_update_check" ]; then
  exec /usr/bin/naabu "$disable_update_check" "$@"
fi
exec /usr/bin/naabu "$@"
